/**
 * Declarative Registry for Classical Islamic Exegesis (Tafseer)
 * Single Source of Truth for source paths, scholarship biographies, and UI metadata.
 */
export const TAFSEER_CONFIG = [
  {
    id: 'tabari',
    hashSlug: 'tabari',
    name: 'Tafsir Al-Tabari',
    displayTitle: 'Tafsir Al-Tabari (AD 883)',
    scholar: "Abu Ja'far Muhammad ibn Jarir al-Tabari (224–310 AH / 839–923 AD)",
    date: 'AD 883',
    era: 'Classical Sunni Exegesis • AD 883',
    era_arabic: 'تفسير أهل السنة والجماعة • ٨٨٣ م',
    defaultPath: 'src/data/quran/commentary/tafsir_tabari_english.json',
    arabicPath: 'src/data/quran/commentary/tafsir_tabari_arabic.json',
    translationNote: "Translation generated by Gemini 3.1 Pro using Tafsir Ibn Kathir and Droge's English translation as templates.",
    sources: {
      ar: {
        label: 'المصدر (جامعة الملك سعود)',
        urlTemplate: 'https://quran.ksu.edu.sa/tafseer/tabary/sura{surah}-aya{ayah}.html'
      },
      en: {
        label: 'Arabic Source (KSU)',
        urlTemplate: 'https://quran.ksu.edu.sa/tafseer/tabary/sura{surah}-aya{ayah}.html'
      }
    },
    envKey: 'TABARI_PATH',
    authority: {
      lead: "The Foundational Exegesis (Jami' al-Bayan): Abu Ja'far Muhammad ibn Jarir al-Tabari produced the earliest comprehensive Quranic commentary to survive intact. Completed around AD 883, it established the definitive paradigm of Tafsir bil-Ma'thur (interpretation strictly anchored in documented apostolic tradition, Sahaba consensus, and earliest classical Arabic grammar).",
      detail: "Universal Scholarly Precedent: All subsequent classical Sunni scholars—including Ibn Kathir, Al-Baghawi, and Al-Qurtubi—relied directly upon Al-Tabari's recorded transmission chains (isnad) and theological precedents as their primary benchmark."
    }
  },
  {
    id: 'ibn_kathir',
    hashSlug: 'kathir',
    name: 'Tafsir Ibn Kathir',
    displayTitle: 'Tafsir Ibn Kathir (AD 1373)',
    scholar: 'Hafiz Imad ad-Din Ismail ibn Kathir (701–774 AH / 1301–1373 AD)',
    date: 'AD 1373',
    era: 'Classical Sunni Exegesis • AD 1373',
    era_arabic: 'تفسير أهل السنة والجماعة • ١٣٧٣ م',
    defaultPath: 'src/data/quran/commentary/tafsir_ibn_kathir_catena.json',
    arabicPath: 'src/data/quran/commentary/tafsir_ibn_kathir_arabic.json',
    translationNote: 'This translation is based on the original Arabic text and the Tafsir Ibn Kathir (Abridged) by Darussalam.',
    sources: {
      ar: {
        label: 'المصدر (جامعة الملك سعود)',
        urlTemplate: 'https://quran.ksu.edu.sa/tafseer/katheer/sura{surah}-aya{ayah}.html'
      },
      en: {
        label: 'English Source (Darussalam)',
        url: 'https://archive.org/embed/TafsirIbnKathirVolume0110English_201702'
      }
    },
    envKey: 'IBN_KATHIR_PATH',
    authority: {
      lead: "Universal Sunni Consensus (Tafsir al-Qur'an al-Azim): Hafiz Ibn Kathir is universally regarded across all major orthodox Sunni schools (traditional, Salafi, Ash'ari) as the most authoritative classical exegesis, praised for strictly interpreting the Quran through the Quran itself and authenticated Hadith.",
      detail: "Standard Edition: Sourced from the standard 10-volume English edition published by Dar-us-Salam Publications (supervised by Shaykh Safiur-Rahman Al-Mubarakpuri), the most widely distributed English Quranic commentary worldwide."
    }
  }
];

/**
 * Resolves concrete source label and URL for a scholar config given the active surah and ayah.
 */
export function resolveScholarSources(config, surah, ayah) {
  if (!config.sources) return {};
  const resolved = {};
  for (const [lang, def] of Object.entries(config.sources)) {
    if (!def) continue;
    let url = def.url;
    if (!url && def.urlTemplate && surah && ayah) {
      url = def.urlTemplate.replace('{surah}', surah).replace('{ayah}', ayah);
    }
    if (url) {
      resolved[lang] = {
        label: def.label,
        url
      };
    }
  }
  return resolved;
}

